vsync = true;
backend = "glx";

animations = true;

# Shadows
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.75;

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = true; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
};

# Opacity (optional, for transparency)
active-opacity = 0.9;
inactive-opacity = 1;

# Blur
blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;
blur-method = "dual_kawase";
blur-strength = 10;
